[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'


# other plugins

[[plugins]] # lightline
repo = 'itchyny/lightline.vim'

[[plugins]] # git
repo = 'tpope/vim-fugitive'

[[plugins]] # git 差分表示
repo = 'airblade/vim-gitgutter'

[[plugins]] # 整形
repo = 'junegunn/vim-easy-align'

[[plugins]] # go lang
repo = 'fatih/vim-go'

[[plugins]] # vue
repo = 'posva/vim-vue'

[[plugins]] # NERDTree
repo = 'scrooloose/nerdtree'

[[plugins]] # NERDTree
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]] # NERDTreeにgitの変更マークを表示
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]] # カラースキーム
repo = 'w0ng/vim-hybrid'

[[plugins]] # vue
repo = 'posva/vim-vue'

[[plugins]] # emmet
repo = 'mattn/emmet-vim'

[[plugins]] # 置換可視化
repo = 'osyo-manga/vim-over'

[[plugins]] # 検索
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
      \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
      \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
      \ <bang>0)
'''

[[plugins]] # コメントアウト
repo = 'tomtom/tcomment_vim'

[[plugins]] # 補完
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
